[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    
build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D ESP32_PARALLEL=1
    -D TFT_PARALLEL_8_BIT=1
    ; --- FUENTES REQUERIDAS (¡EL FIX DE LAS LETRAS!) ---
    -D LOAD_GLCD=1  ; Fuente estándar de Arduino (muy ligera)
    -D LOAD_FONT2=1 ; Fuente pequeña de 16px
    -D LOAD_FONT4=1 ; Fuente mediana de 26px
    
    ; --- BUS DE DATOS ---
    -D TFT_D0=27
    -D TFT_D1=26
    -D TFT_D2=25
    -D TFT_D3=15
    -D TFT_D4=4
    -D TFT_D5=14
    -D TFT_D6=22
    -D TFT_D7=21
    
    ; --- SEÑALES DE CONTROL ---
    -D TFT_RST=32
    -D TFT_CS=33
    -D TFT_DC=2
    -D TFT_WR=12
    -D TFT_RD=13